MVCTravelAgency/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MVCTravelAgency.Helpers;
using MVCTravelAgency.Interfaces;
using MVCTravelAgency.Models;
using MVCTravelAgency.ViewModels;

namespace MVCTravelAgency.Controllers
{
   
    public class AdminController : Controller
    {
        private ITourRepository _tourRepository;
        private IHostingEnvironment _hostingEnvironment;
        public AdminController(ITourRepository tourRepository, IHostingEnvironment hostingEnvironment)
        {
            _tourRepository = tourRepository;
            _hostingEnvironment = hostingEnvironment;
        }
        public IActionResult Index()
        {
            return View();
        }
        /////////////////////Create

        [HttpGet]
        public ViewResult CreateTour()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateTour(TourCreateVM model)
        {
            if (ModelState.IsValid)
            {
                string uniqImgName = ImageHelper.SaveImage(_hostingEnvironment, model.Img);
                string uniqImgLargeName = ImageHelper.SaveImage(_hostingEnvironment, model.ImgLarge);

                Tour newTour = new Tour
                {
                    Name = model.Name,
                    Description = model.Description,
                    DepartureTown = model.DepartureTown,
                    DepartureDate = model.DepartureDate,
                    Countries = model.Countries,
                    IsNightCrossing = model.IsNightCrossing,
                    isFavorite = model.isFavorite,
                    Period = model.Period,
                    Price = model.Price,
                    Img = uniqImgName,
                    ImgLarge = uniqImgLargeName,
                };

                _tourRepository.CreateTour(newTour);

                return Redirect("/Home/Index");
            }
            return View();
        }

        /////////////////////Delete
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteTour(int id)
        {
            Tour tour = _tourRepository.GetTourById(id);
            if (tour != null)
            {
                ImageHelper.DeleteImage(_hostingEnvironment, tour.Img);
                _tourRepository.DeleteTour(tour);
            }
            return Redirect("/Home/Index");
        }

        /////////////////////Edit
        [HttpGet]
        public ViewResult EditTour(int id)
        {
            Tour tour = _tourRepository.GetTourById(id);
            if (tour != null)
            {
                TourEditVM tourEditVM = new TourEditVM
                {
                    Id = tour.Id,
                    Name = tour.Name,
                    Description = tour.Description,
                    DepartureTown = tour.DepartureTown,
                    DepartureDate = tour.DepartureDate,
                    Countries = tour.Countries,
                    IsNightCrossing = tour.IsNightCrossing,
                    isFavorite = tour.isFavorite,
                    Period = tour.Period,
                    Price = tour.Price,
                    ExistImgName = tour.Img,
                    ExistImgLargeName = tour.ImgLarge
                };
                return View(tourEditVM);
            }
            else
            {
                NotFound();
            }
            return View();
        }

        [HttpPost]
        public IActionResult EditTour(TourEditVM model)
        {
            if (ModelState.IsValid)
            {
                Tour newTour = new Tour
                {
                    Id = model.Id,
                    Name = model.Name,
                    Description = model.Description,
                    DepartureTown = model.DepartureTown,
                    DepartureDate = model.DepartureDate,
                    Countries = model.Countries,
                    IsNightCrossing = model.IsNightCrossing,
                    isFavorite = model.isFavorite,
                    Period = model.Period,
                    Price = model.Price,

                    Img = ChangePhoto(model.ExistImgName, model.Img),
                    ImgLarge = ChangePhoto(model.ExistImgLargeName, model.ImgLarge),
                };

                _tourRepository.EditTour(newTour);
                return Redirect("/Home/Index");
            }
            return View();
        }

        public string ChangePhoto(string old, IFormFile newPhoto)
        {
            //Якщо вибрали нове фото
            if (newPhoto != null)
            {
                if (old != null)
                {
                    ImageHelper.DeleteImage(_hostingEnvironment, old);
                }
                string imageName = ImageHelper.SaveImage(_hostingEnvironment, newPhoto);
                return imageName;
            }
            //Якщо не вибирали нове фото
            return old;
        }
    }
}

MVCTravelAgency/Controllers/TourController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MVCTravelAgency.Interfaces;
using MVCTravelAgency.Models;
using System.Collections.Generic;
using System.Linq;

namespace MVCTravelAgency.Controllers
{
    public class TourController : Controller
    {
        private readonly ITourRepository _tourRepository;
        private readonly ILogger logger;
        public TourController(ITourRepository tourRepository, ILogger<TourController> logger)
        {
            _tourRepository = tourRepository;
            this.logger = logger;
        }
        [Route("Tour/Index/{id}")]
        public IActionResult Tour(int id)
        {
            var tour = _tourRepository.GetTourById(id);

            return View(tour);
        }
        public IActionResult Index()
        {
            List<Tour> Tours = _tourRepository.GetAllTours().ToList();
            return View(Tours);
        }
    }
}

MVCTravelAgency/Views/Shared/_Layout.cshtml
@inject SignInManager<AppUser> signInManager;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["TravelAgency"] - MVCTravelAgency</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script|Montserrat:400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/main.css" />
</head>
<body>
    <header class="header">
        <div class="container">
            <div class="header__inner">
                <div class="header__logo">
                    <a class="header__link" asp-area="" asp-controller="Home" asp-action="Index">TopTravel</a>
                </div>
                <nav class="nav">
                    <a class="nav__link" asp-area="" asp-controller="Tour" asp-action="Index">Тури</a>
                    <a class="nav__link" id="nav__admin" asp-area="" asp-controller="Admin" asp-action="Index">Адмін</a>
                    <a class="nav__link" asp-area="" asp-controller="Home" asp-action="Privacy">Про нас</a>
                    @if (signInManager.IsSignedIn(User))
                    {
                        <form method="post" asp-controller="Account" asp-action="Logout">
                            <button type="submit" class="nav__link  nav__logout"> Вихід @User.Identity.Name</button>
                        </form>
                    }
                    else
                    {
                        <a class="nav__link" asp-area="" asp-controller="Account" asp-action="Register">Реєстрація</a>
                        <a class="nav__link" asp-area="" asp-controller="Account" asp-action="Login">Вхід</a>
                    }
                </nav>
            </div>
        </div>
    </header>

    @RenderBody()

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>